-- Ayllu · esquema de Supabase (Postgres)
-- 10 tablas + 8 índices. Ejecutar en el SQL Editor del proyecto.
-- Si no creas este esquema, la app funciona igual con la semilla en memoria.

create table if not exists languages (
    id          bigint generated by default as identity primary key,
    code        text not null unique,
    name        text not null,
    "nativeName" text,
    family      text,
    flores200   boolean default true,
    speakers    text,
    active      boolean default true,
    "group"     text,
    google      text,
    lexicon     boolean default false
);
alter table languages add column if not exists "group" text;
alter table languages add column if not exists google text;
alter table languages add column if not exists lexicon boolean default false;

create table if not exists communities (
    id          bigint generated by default as identity primary key,
    name        text not null,
    ecosystem   text not null,
    "langCode"  text references languages(code),
    family      text,
    altitude    integer default 0,
    description text,
    students    integer default 0
);

create table if not exists students (
    id           bigint generated by default as identity primary key,
    name         text not null,
    "communityId" bigint references communities(id) on delete set null,
    "langCode"   text references languages(code),
    pre          numeric default 0,
    post         numeric default 0,
    cohort       text default 'A',
    attendance   integer default 0
);

create table if not exists glossary (
    id         bigint generated by default as identity primary key,
    term       text not null,
    langs      jsonb not null default '{}'::jsonb,
    domain     text default 'general',
    validated  boolean default false,
    "updatedBy" text default 'api'
);

create table if not exists materials (
    id        bigint generated by default as identity primary key,
    title     text not null,
    kind      text default 'lectura',
    "langCode" text,
    level     text default 'todos',
    size      text default '—',
    snippet   text
);

create table if not exists feedback (
    id         bigint generated by default as identity primary key,
    "studentId" bigint references students(id) on delete set null,
    rating     integer check (rating between 1 and 5),
    note       text,
    reviewer   text default 'anónimo',
    "createdAt" timestamptz default now()
);

create table if not exists events (
    id        bigint generated by default as identity primary key,
    kind      text not null,
    "langCode" text,
    snippet   text,
    "chrF2"   numeric default 0,
    actor     text default 'api',
    ts        timestamptz default now()
);

-- Las cuentas de autenticación siguen en la configuración de la app.
-- Esta tabla guarda solo perfiles públicos; nunca almacena contraseñas.
create table if not exists users (
    id            bigint generated by default as identity primary key,
    email         text not null unique,
    role          text not null check (role in ('docente', 'estudiante')),
    name          text not null,
    "jobTitle"    text,
    "langCode"    text references languages(code),
    "communityId" bigint references communities(id) on delete set null,
    "studentName" text
);

create index if not exists idx_students_community on students("communityId");
create index if not exists idx_students_lang      on students("langCode");
create index if not exists idx_community_lang     on communities("langCode");
create index if not exists idx_glossary_domain    on glossary(domain);
create index if not exists idx_events_ts          on events(ts desc);

-- ---------------------------------------------------------------------------
-- v5 · mensajería docente ↔ estudiante: conversaciones y mensajes
-- (el núcleo en memoria usa las tablas «threads» y «messages»)
-- ---------------------------------------------------------------------------

create table if not exists threads (
    id           bigint generated by default as identity primary key,
    title        text not null,
    type         text default 'direct',          -- direct | group
    "createdBy"  bigint references users(id) on delete set null,
    "createdByName" text,
    participants bigint[] not null default '{}', -- ids de usuarios del hilo
    "communityId" bigint references communities(id) on delete set null,
    "createdAt"  timestamptz default now()
);

create table if not exists messages (
    id          bigint generated by default as identity primary key,
    "threadId"  bigint references threads(id) on delete cascade,
    "fromUserId" bigint,
    "toUserId"  bigint,
    "fromRole"  text,
    "toRole"    text,
    "fromName"  text,
    "toName"    text,
    "studentId" bigint references students(id) on delete set null,
    "studentName" text,
    kind        text default 'mensaje',          -- mensaje | material | documento
    title       text default '',
    src         text,
    tgt         text,
    "srcText"   text,                            -- ORIGINAL intacto de quien escribe
    "outText"   text,                            -- traducción que lee el destinatario
    "originEs"  text default '',
    provider    text,
    engine      text,
    degraded    boolean default true,
    coverage    numeric default 0,
    "chrF2"     numeric default 0,
    glossary    jsonb default '[]',
    notes       jsonb default '[]',
    translations jsonb default '{}',             -- caché de traducciones bajo demanda
    attachment  jsonb,                           -- adjunto .pdf/.txt (texto + bytes en base64)
    "readBy"    jsonb default '[]',
    "createdAt" timestamptz default now(),
    "readAt"    timestamptz
);

create index if not exists idx_threads_participants on threads using gin(participants);
create index if not exists idx_messages_thread      on messages("threadId", "createdAt" desc);
create index if not exists idx_messages_from        on messages("fromUserId");
alter table messages add column if not exists engine text;

-- Nota de honestidad: el texto que escribió cada persona vive intacto en
-- "srcText" y la traducción que lee la otra parte en "outText". «translations»
-- guarda las traducciones pedidas con el botón «Traducir» de cualquiera de los
-- dos roles y «attachment» el documento adjunto validado por el escáner.
